// lib/mock-data.ts - Seed data for multi-campus support and services
import { Campus, CampusLocation, Shop, CatalogCategory, CatalogItem, Order, User } from './types';

export const MOCK_CAMPUSES: Campus[] = [
  {
    id: 'campus-iitp-bihta',
    name: 'IIT Patna (Bihta Campus)',
    slug: 'iit-patna-bihta',
    code: 'IITP-BIHTA',
    center_lat: 25.5357,
    center_lng: 84.8512,
    radius_meters: 4500,
    is_active: true,
    tagline: 'Main Campus, Bihta, Bihar',
    image_url: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'campus-iitk',
    name: 'IIT Kanpur',
    slug: 'iit-kanpur',
    code: 'IITK',
    center_lat: 26.5123,
    center_lng: 80.2329,
    radius_meters: 5000,
    is_active: true,
    tagline: 'Kalyanpur, Kanpur, Uttar Pradesh',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'campus-nitp',
    name: 'NIT Patna',
    slug: 'nit-patna',
    code: 'NITP',
    center_lat: 25.6207,
    center_lng: 85.1724,
    radius_meters: 3000,
    is_active: true,
    tagline: 'Ashok Rajpath, Patna, Bihar',
    image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80',
  },
];

export const MOCK_CAMPUS_LOCATIONS: CampusLocation[] = [
  {
    id: 'loc-1',
    campus_id: 'campus-iitp-bihta',
    name: 'Aryabhatta Hostel (Boys Hostel Block A)',
    type: 'BOYS_HOSTEL',
    delivery_allowed_at_door: false,
  },
  {
    id: 'loc-2',
    campus_id: 'campus-iitp-bihta',
    name: 'Chanakya Hostel (Boys Hostel Block B)',
    type: 'BOYS_HOSTEL',
    delivery_allowed_at_door: false,
  },
  {
    id: 'loc-3',
    campus_id: 'campus-iitp-bihta',
    name: 'Gargi Hostel (Girls Hostel)',
    type: 'GIRLS_HOSTEL',
    delivery_allowed_at_door: false,
  },
  {
    id: 'loc-4',
    campus_id: 'campus-iitp-bihta',
    name: 'Central Library Courtyard',
    type: 'LIBRARY',
    delivery_allowed_at_door: true,
  },
  {
    id: 'loc-5',
    campus_id: 'campus-iitp-bihta',
    name: 'Academic Complex / Block 3',
    type: 'ACADEMIC_BLOCK',
    delivery_allowed_at_door: true,
  },
  {
    id: 'loc-6',
    campus_id: 'campus-iitp-bihta',
    name: 'Main Campus Security Gate 1',
    type: 'CAMPUS_GATE',
    delivery_allowed_at_door: true,
  },
];

export const MOCK_SHOPS: Shop[] = [
  {
    id: 'shop-yumquick',
    campus_id: 'campus-iitp-bihta',
    name: 'YumQuick Night Canteen',
    slug: 'yumquick-night-canteen',
    service_type: 'FOOD_DINING',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=500&q=80',
    description: 'Hot meals, shakes, burgers & late-night munchies delivered directly to hostel gates.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: true,
    delivery_fee: 10,
    min_order_for_free_delivery: 150,
    prep_time_minutes: 20,
    upi_vpa: 'yumquick@upi',
    phone: '9876543210',
    rating: 4.8,
    tags: ['Burgers', 'Shakes', 'Night Mess', 'Pasta'],
    banner_text: 'Open till 3:00 AM • Free Delivery above ₹150',
  },
  {
    id: 'shop-nescafe',
    campus_id: 'campus-iitp-bihta',
    name: 'Nescafe & Juice Kiosk',
    slug: 'nescafe-juice-kiosk',
    service_type: 'FOOD_DINING',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=500&q=80',
    description: 'Cold coffee, iced teas, fresh fruit juices, and instant grilled sandwiches.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: true,
    delivery_fee: 10,
    min_order_for_free_delivery: 100,
    prep_time_minutes: 15,
    upi_vpa: 'nescafekiosk@upi',
    phone: '9876543211',
    rating: 4.6,
    tags: ['Cold Coffee', 'Sandwiches', 'Juices', 'Tea'],
    banner_text: 'Fresh Sandwiches & Beverages',
  },
  {
    id: 'shop-rolls',
    campus_id: 'campus-iitp-bihta',
    name: 'Campus Kathi Rolls & Biryani',
    slug: 'campus-kathi-rolls',
    service_type: 'FOOD_DINING',
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80',
    description: 'Crispy egg, paneer, and chicken rolls prepared fresh with mint chutney.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: true,
    delivery_fee: 15,
    min_order_for_free_delivery: 200,
    prep_time_minutes: 25,
    upi_vpa: 'campusrolls@upi',
    phone: '9876543212',
    rating: 4.7,
    tags: ['Kathi Rolls', 'Biryani', 'Chaat'],
    banner_text: 'Student Special Combo: Roll + Drink at ₹119',
  },
  {
    id: 'shop-salon',
    campus_id: 'campus-iitp-bihta',
    name: 'Urban Campus Salon & Grooming',
    slug: 'urban-campus-salon',
    service_type: 'SALON_GROOMING',
    image_url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=500&q=80',
    description: 'Student haircut, beard styling, head massage, and facial appointments at student center.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: false,
    delivery_fee: 0,
    prep_time_minutes: 30,
    upi_vpa: 'campussalon@upi',
    phone: '9876543213',
    rating: 4.9,
    tags: ['Haircut', 'Beard Trim', 'Head Massage', 'Facial'],
    banner_text: 'Pre-book slots without waiting in hostel lines',
  },
  {
    id: 'shop-laundry',
    campus_id: 'campus-iitp-bihta',
    name: 'Sparkle Campus Laundry',
    slug: 'sparkle-campus-laundry',
    service_type: 'LAUNDRY',
    image_url: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=500&q=80',
    description: 'Hostel doorstep bag pickup, wash, steam iron, and folded return within 24 hours.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: true,
    delivery_fee: 15,
    prep_time_minutes: 60,
    upi_vpa: 'sparklelaundry@upi',
    phone: '9876543214',
    rating: 4.5,
    tags: ['Wash & Iron', 'Dry Clean', 'Doorstep Pickup'],
    banner_text: 'Per kg wash & iron with hostel delivery',
  },
  {
    id: 'shop-print',
    campus_id: 'campus-iitp-bihta',
    name: 'Speedy Printouts & Stationery',
    slug: 'speedy-printouts',
    service_type: 'PRINT_STATIONERY',
    image_url: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=500&q=80',
    description: 'Upload PDF lab manuals, thesis, or notes and get bound printouts delivered before class.',
    is_open: true,
    is_snoozed: false,
    delivery_enabled: true,
    delivery_fee: 10,
    prep_time_minutes: 15,
    upi_vpa: 'speedyprint@upi',
    phone: '9876543215',
    rating: 4.8,
    tags: ['Color Print', 'Spiral Binding', 'Lab Reports', 'Stationery'],
    banner_text: 'Instant PDF printout delivery to Hostel Gate',
  },
];

export const MOCK_CATEGORIES: CatalogCategory[] = [
  { id: 'cat-1', shop_id: 'shop-yumquick', name: 'Snacks & Starters', display_order: 1 },
  { id: 'cat-2', shop_id: 'shop-yumquick', name: 'Main Meals', display_order: 2 },
  { id: 'cat-3', shop_id: 'shop-yumquick', name: 'Shakes & Drinks', display_order: 3 },
  { id: 'cat-4', shop_id: 'shop-yumquick', name: 'Desserts', display_order: 4 },
  { id: 'cat-5', shop_id: 'shop-salon', name: 'Hair Services', display_order: 1 },
  { id: 'cat-6', shop_id: 'shop-salon', name: 'Grooming & Spa', display_order: 2 },
];

export const MOCK_ITEMS: CatalogItem[] = [
  // YumQuick Food Items (matching Figma YumQuick node 1:423)
  {
    id: 'item-shake',
    shop_id: 'shop-yumquick',
    category_id: 'cat-3',
    name: 'Strawberry Shake',
    description: 'Fresh strawberry blend with vanilla ice cream and whipped topping.',
    price: 120,
    discounted_price: 99,
    image_url: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    bestseller: true,
  },
  {
    id: 'item-lasagna',
    shop_id: 'shop-yumquick',
    category_id: 'cat-2',
    name: 'Broccoli Lasagna',
    description: 'Baked layers of pasta, tender broccoli florets, creamy bechamel, and melted mozzarella.',
    price: 180,
    discounted_price: 159,
    image_url: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    bestseller: true,
  },
  {
    id: 'item-burger',
    shop_id: 'shop-yumquick',
    category_id: 'cat-1',
    name: 'Crispy Chicken Burger',
    description: 'Golden fried chicken patty with iceberg lettuce, secret spicy mayo, and pickles.',
    price: 140,
    discounted_price: 129,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
    is_veg: false,
    is_available: true,
    bestseller: true,
  },
  {
    id: 'item-curry',
    shop_id: 'shop-yumquick',
    category_id: 'cat-2',
    name: 'Chicken Curry with Steamed Rice',
    description: 'Homestyle spicy chicken curry served with fragrant basmati rice and pickle.',
    price: 210,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80',
    is_veg: false,
    is_available: true,
  },
  {
    id: 'item-veg-burger',
    shop_id: 'shop-yumquick',
    category_id: 'cat-1',
    name: 'Bean & Veggie Burger',
    description: 'Spiced kidney bean patty, fresh tomato, cucumber slices, and mint yoghurt spread.',
    price: 110,
    discounted_price: 89,
    image_url: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
  },
  {
    id: 'item-cheesecake',
    shop_id: 'shop-yumquick',
    category_id: 'cat-4',
    name: 'Strawberry Cheesecake',
    description: 'New York style cheesecake slice topped with sweet strawberry compote.',
    price: 150,
    image_url: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
  },
  {
    id: 'item-latte',
    shop_id: 'shop-yumquick',
    category_id: 'cat-3',
    name: 'Iced Coffee Latte',
    description: 'Double espresso shot chilled over milk and lightly sweetened.',
    price: 90,
    discounted_price: 79,
    image_url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
  },
  // Nescafe Items
  {
    id: 'item-coldcoffee',
    shop_id: 'shop-nescafe',
    category_id: 'cat-3',
    name: 'Classic Cold Coffee Frappe',
    description: 'Thick creamy Nescafe cold coffee with chocolate drizzle.',
    price: 60,
    image_url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    bestseller: true,
  },
  {
    id: 'item-maggi',
    shop_id: 'shop-nescafe',
    category_id: 'cat-1',
    name: 'Double Masala Cheese Maggi',
    description: 'Campus midnight essential: two cakes of Maggi with vegetables and grated cheese.',
    price: 70,
    image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    bestseller: true,
  },
  // Salon Services (Extensibility proof)
  {
    id: 'item-haircut',
    shop_id: 'shop-salon',
    category_id: 'cat-5',
    name: 'Student Classic Haircut & Style',
    description: 'Professional precision scissor & trimmer haircut with hair wash.',
    price: 100,
    image_url: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    duration_minutes: 25,
    bestseller: true,
  },
  {
    id: 'item-beard',
    shop_id: 'shop-salon',
    category_id: 'cat-6',
    name: 'Beard Trim & Razor Lineup',
    description: 'Beard shaping, hot towel treatment, and aftershave balm.',
    price: 60,
    image_url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=400&q=80',
    is_veg: true,
    is_available: true,
    duration_minutes: 15,
  },
];

export const MOCK_ACTIVE_ORDERS: Order[] = [
  {
    id: 'ord-10492',
    order_number: 'GB-BIH-10492',
    campus_id: 'campus-iitp-bihta',
    campus_name: 'IIT Patna (Bihta)',
    shop_id: 'shop-yumquick',
    shop_name: 'YumQuick Night Canteen',
    customer_id: 'user-student-1',
    customer_name: 'Anurag Mishra',
    customer_phone: '9876543299',
    address_summary: 'Aryabhatta Hostel (Block A), Room 312 • Gate Drop-off',
    status: 'OUT_FOR_DELIVERY',
    delivery_pin: '7492', // Active 4-digit code to show customer
    items_subtotal: 228,
    delivery_fee: 10,
    platform_fee: 5,
    tax_fee: 0,
    total_amount: 243,
    estimated_delivery_time: '12 mins (Arriving by 01:45 AM)',
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-10492',
        catalog_item_id: 'item-shake',
        item_name: 'Strawberry Shake',
        unit_price: 99,
        quantity: 1,
        total_price: 99,
      },
      {
        id: 'oi-2',
        order_id: 'ord-10492',
        catalog_item_id: 'item-burger',
        item_name: 'Crispy Chicken Burger',
        unit_price: 129,
        quantity: 1,
        total_price: 129,
      },
    ],
  },
  {
    id: 'ord-10491',
    order_number: 'GB-BIH-10491',
    campus_id: 'campus-iitp-bihta',
    campus_name: 'IIT Patna (Bihta)',
    shop_id: 'shop-nescafe',
    shop_name: 'Nescafe & Juice Kiosk',
    customer_id: 'user-student-1',
    customer_name: 'Anurag Mishra',
    customer_phone: '9876543299',
    address_summary: 'Aryabhatta Hostel (Block A), Room 312',
    status: 'DELIVERED',
    delivery_pin: '1823',
    items_subtotal: 130,
    delivery_fee: 10,
    platform_fee: 5,
    tax_fee: 0,
    total_amount: 145,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    delivered_at: new Date(Date.now() - 2.5 * 3600000).toISOString(),
    items: [
      {
        id: 'oi-3',
        order_id: 'ord-10491',
        catalog_item_id: 'item-coldcoffee',
        item_name: 'Classic Cold Coffee Frappe',
        unit_price: 60,
        quantity: 1,
        total_price: 60,
      },
      {
        id: 'oi-4',
        order_id: 'ord-10491',
        catalog_item_id: 'item-maggi',
        item_name: 'Double Masala Cheese Maggi',
        unit_price: 70,
        quantity: 1,
        total_price: 70,
      },
    ],
  },
];

export const CURRENT_USER: User = {
  id: 'user-student-1',
  name: 'Anurag Mishra',
  phone: '9876543299',
  email: 'anurag@campus.edu',
  phone_verified: true,
  role: 'CUSTOMER', // Can be dynamically switched in demo header
  active_campus_id: 'campus-iitp-bihta',
  is_active: true,
};
